coverage:
  branch: main
  # Don't trigger CI failure on coverage reduction, avoid CI errors from false
  # positives on this when changes are tiny/trivial/doc only.
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
